global:
  scrape_interval: 15s  # 스크랩 간격 설정

scrape_configs:
  - job_name: 'spring-boot'  # 잡 이름 설정
    metrics_path: '/actuator/prometheus'  # 메트릭 경로 설정
    static_configs:
      - targets: ['host.docker.internal:8080']  # 메트릭을 스크랩할 대상 설정
    scheme: https  # HTTPS를 사용하도록 설정
    tls_config:
      ca_file: ./cert/ca_bundle.crt  # CA 인증서 파일 경로 설정
      cert_file: ./cert/certificate.crt  # 클라이언트 인증서 파일 경로 설정
      key_file: ./cert/private.key  # 클라이언트 인증서 키 파일 경로 설정
      insecure_skip_verify: true  # 인증서 검증을 건너뛰려면 true로 설정 (권장되지 않음)